name: Build

on:
  workflow_call: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Render resume markdown to pages
        uses: wranders/markdown-to-pages-action@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            resume.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages-dist
          path: dist
