name: Deploy

on:
  workflow_call: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Pages artifact
        uses: actions/download-artifact@v4
        with:
          name: pages-dist
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
        with:
          artifact_name: pages-dist
