name: Serve Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    uses: ./.github/workflows/release.yml

  build:
    needs: release
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
