name: Serve Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tag:
    uses: ./.github/workflows/tag.yml

  release:
    needs: tag
    uses: ./.github/workflows/release.yml

  build_html:
    needs: release
    uses: ./.github/workflows/build_html.yml

  build_pdf:
    needs: release
    uses: ./.github/workflows/build_pdf.yml

  deploy:
    needs:
      - build-html
      - build-pdf
    if: always()
    uses: ./.github/workflows/deploy.yml
